// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPQBa-TD6z1DMz9_G1efIn_h66o-A5Bk',
    appId: '1:749276396628:android:d2e1af20c0e17afa7941c1',
    messagingSenderId: '749276396628',
    projectId: 'fir-push-notification-999fb',
    storageBucket: 'fir-push-notification-999fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGd5UFuE1tvSVs8mCDXo7KYCBvTL5vmw',
    appId: '1:749276396628:ios:58649370bfd527ce7941c1',
    messagingSenderId: '749276396628',
    projectId: 'fir-push-notification-999fb',
    storageBucket: 'fir-push-notification-999fb.appspot.com',
    iosClientId: '749276396628-bibrdprbtrllqlgs4pgi8catpirkaims.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
